import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Clock, Mail, MapPin, Menu, MessageCircle, X } from 'lucide-react';
import './styles.css';

const SITE = { name: 'Super Magras', legalName: 'Gilberto da Silva', cnpj: '68.034.728/0001-78', email: 'comercial@supermagras.online', phoneDisplay: '+55 (84) 8193-3645', whatsappNumber: '558481933645', address: ['Av. Industrial, 1223', 'Nossa Senhora da Apresentação', 'Natal/RN', 'CEP 59.114-268'] };
const wa = () => `https://wa.me/${SITE.whatsappNumber}?text=${encodeURIComponent('Olá! Quero saber mais sobre o protocolo Super Magras.')}`;
const path = () => window.location.pathname.replace(/\/$/, '') || '/';
const go = (href: string) => { history.pushState(null, '', href); window.dispatchEvent(new PopStateEvent('popstate')); scrollTo({ top: 0, behavior: 'smooth' }); };

const steps = [{ n: '01', t: 'Avaliação inicial', d: 'Conversamos para entender seu histórico, rotina, objetivos e dificuldades.' }, { n: '02', t: 'Plano personalizado', d: 'Montamos um protocolo desenhado para sua vida real, com alimentação, hábitos e orientações práticas.' }, { n: '03', t: 'Acompanhamento contínuo', d: 'Você é acompanhada de perto, com ajustes ao longo da jornada e suporte para manter constância.' }, { n: '04', t: 'Manutenção e autonomia', d: 'Você sai com autonomia, novos hábitos e ferramentas para manter os resultados.' }];
const faqs = [{ q: 'Para quem é o protocolo Super Magras?', a: 'Para mulheres adultas que querem emagrecer de forma saudável, com acompanhamento. Não é indicado para gestantes, lactantes, menores de 18 anos ou pessoas com condições clínicas sem orientação médica.' }, { q: 'Em quanto tempo vejo resultado?', a: 'Cada corpo responde em um ritmo. Resultados dependem de comprometimento, rotina e fatores individuais.' }, { q: 'Preciso parar de comer o que gosto?', a: 'Não. O protocolo é construído para ser sustentável, encontrando equilíbrio dentro da sua realidade.' }, { q: 'Substitui acompanhamento médico?', a: 'Não. O conteúdo é educativo e recomendamos acompanhamento com médico, nutricionista ou profissional de saúde habilitado.' }];

function App() { const [route, setRoute] = useState(path()); useEffect(() => { const on = () => setRoute(path()); addEventListener('popstate', on); return () => removeEventListener('popstate', on); }, []); return <><Header />{route === '/protocolos' ? <Protocolos /> : route === '/contato' ? <Contato /> : route === '/politica-de-privacidade' ? <Legal title="Política de Privacidade" type="privacy" /> : route === '/termos-de-uso' ? <Legal title="Termos de Uso" type="terms" /> : route === '/isencao-de-responsabilidade' ? <Legal title="Isenção de Responsabilidade" type="disclaimer" /> : <Home />}<Footer /><a className="fab" href={wa()} target="_blank" aria-label="Falar no WhatsApp"><MessageCircle /></a></>; }

function Header() { const [open, setOpen] = useState(false); const links = [['/', 'Início'], ['/protocolos', 'Protocolos'], ['/contato', 'Contato']]; return <header><div className="nav"><button className="brand" onClick={() => go('/')}>Super Magras</button><nav>{links.map(([href, label]) => <button key={href} onClick={() => go(href)}>{label}</button>)}<a href={wa()} target="_blank">Falar no WhatsApp</a></nav><button className="menu" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div>{open && <div className="drawer">{links.map(([href, label]) => <button key={href} onClick={() => { setOpen(false); go(href); }}>{label}</button>)}<a href={wa()} target="_blank">Falar no WhatsApp</a></div>}</header>; }
function Home() { return <main><section className="hero"><div><p className="eyebrow">Emagrecimento com leveza</p><h1>Um corpo mais leve. <em>Uma vida inteira</em> de saúde.</h1><p>Na Super Magras, cuidamos de mulheres que querem emagrecer de forma saudável, com acompanhamento, protocolos personalizados e constância.</p><div className="actions"><a className="primary" href={wa()} target="_blank">Quero meu protocolo</a><button className="secondary" onClick={() => go('/protocolos')}>Como funciona</button></div></div><div className="visual"><strong>+500</strong><span>mulheres acompanhadas</span></div></section><section className="section alt"><p className="divider"/><h2>Saúde primeiro. Resultados em seguida.</h2><p>Nada de promessas mágicas. O protocolo Super Magras é construído em três pilares simples e poderosos.</p><div className="cards">{['Acompanhamento próximo|Suporte direto para tirar dúvidas, ajustar o plano e celebrar cada conquista.', 'Plano personalizado|Cada protocolo considera rotina, histórico, preferências e objetivos reais.', 'Hábitos sustentáveis|Trabalhamos para que os resultados se mantenham depois do protocolo.'].map((x) => { const [t,d]=x.split('|'); return <article key={t}><h3>{t}</h3><p>{d}</p></article>; })}</div></section><section className="section split"><div className="food"/><div><p className="eyebrow">Nossa missão</p><h2>Emagrecer sem perder a saúde, nem a autoestima.</h2><p>Nascemos para atender mulheres que já tentaram dietas restritivas, fórmulas milagrosas e promessas sem fim. Nosso protocolo coloca a saúde no centro de cada decisão.</p><p>Emagrecer é consequência de cuidar bem do corpo, da mente e da rotina. Com método, suporte e paciência.</p></div></section><section className="section blush"><h2>Histórias que inspiram</h2><div className="cards">{['Amanda, 34|Pela primeira vez emagreci sem passar fome. O acompanhamento muda tudo.', 'Patrícia, 41|Recuperei minha disposição e voltei a me sentir bonita olhando no espelho.', 'Júlia, 29|Aprendi a comer de verdade. O protocolo virou um novo estilo de vida pra mim.'].map((x)=>{const[n,t]=x.split('|');return <article key={n}><blockquote>“{t}”</blockquote><p>{n}</p></article>})}</div><small>Resultados individuais variam de pessoa para pessoa.</small></section><CTA /></main>; }
function Protocolos() { return <main><HeroPage eyebrow="Protocolos" title="Um método feito pra durar." text="Avaliação cuidadosa, plano personalizado e acompanhamento próximo para emagrecimento real, com saúde e sem efeito sanfona."/><section className="section split"><div className="protocol"/><div>{steps.map(s => <article className="step" key={s.n}><span>{s.n}</span><div><h3>{s.t}</h3><p>{s.d}</p></div></article>)}</div></section><section className="section alt"><h2>Perguntas frequentes</h2><div className="faq">{faqs.map(f => <details key={f.q}><summary>{f.q}</summary><p>{f.a}</p></details>)}</div></section><CTA /></main>; }
function Contato() { return <main><HeroPage eyebrow="Contato" title="A gente te responde rapidinho." text="Escolha o canal que prefere. Tiramos suas dúvidas e indicamos o melhor caminho dentro do protocolo Super Magras."/><section className="section"><div className="contact"><a href={wa()} target="_blank"><MessageCircle/><h3>WhatsApp</h3><p>Atendimento ágil, direto com nossa equipe.</p><strong>{SITE.phoneDisplay}</strong></a><a href={`mailto:${SITE.email}`}><Mail/><h3>E-mail</h3><p>Para parcerias, imprensa ou dúvidas detalhadas.</p><strong>{SITE.email}</strong></a><article><MapPin/><h3>Endereço</h3><p>{SITE.address.map(x => <React.Fragment key={x}>{x}<br/></React.Fragment>)}</p></article><article><Clock/><h3>Horário</h3><p>Segunda a sexta<br/>09h às 18h</p></article></div><p className="legal-line">{SITE.name} - {SITE.legalName} - CNPJ {SITE.cnpj}</p></section></main>; }
function Legal({ title, type }: { title: string; type: string }) { return <main><HeroPage eyebrow="Legal" title={title} text={`${SITE.name} - ${SITE.legalName}, CNPJ ${SITE.cnpj}.`} /><section className="section legal"><LegalBody type={type}/><p className="muted">Última atualização: 08/10/2026.</p></section></main>; }
function LegalBody({ type }: { type: string }) { if (type === 'privacy') return <><p>Esta Política explica como a Super Magras coleta, utiliza, armazena e protege dados pessoais em conformidade com a LGPD.</p><h2>Dados coletados</h2><p>Nome, e-mail, telefone/WhatsApp, mensagens enviadas e dados de navegação por cookies e ferramentas de análise.</p><h2>Finalidade</h2><p>Responder mensagens, apresentar protocolos, melhorar a experiência do site e cumprir obrigações legais.</p><h2>Direitos do titular</h2><p>Você pode solicitar acesso, correção, eliminação, anonimização, bloqueio ou revogação do consentimento pelo e-mail {SITE.email}.</p></>; if (type === 'terms') return <><p>Ao navegar pelo site, você concorda com estes Termos de Uso.</p><h2>Objeto</h2><p>O site é informativo e institucional, apresentando protocolos de emagrecimento e serviços da Super Magras.</p><h2>Uso permitido</h2><p>É vedado copiar, reproduzir, modificar ou explorar comercialmente qualquer conteúdo sem autorização.</p><h2>Limitação de responsabilidade</h2><p>Informações são educativas, não substituem acompanhamento profissional e resultados variam individualmente.</p><h2>Foro</h2><p>Fica eleito o foro da Comarca de Natal/RN.</p></>; return <><p>Este site não faz parte do Facebook, Instagram ou Meta Platforms, Inc. e não é endossado por essas plataformas.</p><p>Também não é afiliado, patrocinado ou administrado por Google, YouTube, TikTok, Kwai ou qualquer outra plataforma de anúncios.</p><h2>Resultados individuais</h2><p>Depoimentos e resultados apresentados são individuais e podem variar. Não existe garantia de resultado.</p><h2>Aviso de saúde</h2><p>O conteúdo é informativo e educativo e não substitui consulta, diagnóstico ou tratamento por profissional de saúde habilitado.</p></>; }
function HeroPage({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <section className="pageHero"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p></section>; }
function CTA() { return <section className="cta"><h2>Sua nova história começa com uma conversa.</h2><p>Fale com a nossa equipe e descubra qual protocolo combina com o seu momento.</p><a className="primary" href={wa()} target="_blank">Falar no WhatsApp agora</a></section>; }
function Footer() { return <footer><div className="footergrid"><div><h3>Super Magras</h3><p>Protocolos de emagrecimento com acompanhamento, foco em saúde, constância e resultados sustentáveis.</p></div><div><h4>Navegação</h4>{['/','/protocolos','/contato','/politica-de-privacidade','/termos-de-uso','/isencao-de-responsabilidade'].map((href,i)=><button key={href} onClick={()=>go(href)}>{['Início','Protocolos','Contato','Política de Privacidade','Termos de Uso','Isenção de Responsabilidade'][i]}</button>)}</div><div><h4>Contato</h4><p>WhatsApp: {SITE.phoneDisplay}<br/>E-mail: {SITE.email}<br/>{SITE.address.join(' · ')}</p></div></div><div className="disclaimer"><p><strong>{SITE.name}</strong> - RAZÃO SOCIAL: {SITE.legalName} - CNPJ: {SITE.cnpj}.</p><p>Este site não faz parte do Facebook, Instagram ou Meta Platforms, Inc.; não é endossado pela Meta, Google, YouTube, TikTok, Kwai ou qualquer plataforma de anúncios. Todas as marcas pertencem aos seus respectivos proprietários.</p><p>Resultados individuais variam. O conteúdo é informativo e não substitui consulta, diagnóstico ou tratamento por profissional habilitado.</p><p>© {new Date().getFullYear()} {SITE.name}. Todos os direitos reservados.</p></div></footer>; }

createRoot(document.getElementById('root')!).render(<App />);
